version: '3.1'
services:
  app:
    image: '466bd55a4fe2b469b9176026fd4d766c3caa7b9a38f4505b2ae6b3ebc05d6dee'
    container_name: app
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=rasl_1998
    depends_on:
      - db

  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rasl_1998

